@startuml

actor Administrator
actor Użytkownik

Administrator-->(Zdalna aktualizacja biletomatu)

Użytkownik-->(Płatność wieloma metodami)


Administrator --> (Monitorowanie rynków finansowych)
Administrator --> (Konfiguracja oferty)

Użytkownik --> (Wybór biletu)
(Wybór biletu) --> (Zakup biletu)
Użytkownik --> (Wybór języka)
(Zakup biletu) --> (Otrzymanie potwierdzenia zakupu)

@enduml